#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --nox11\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1
send -- "xterm\r"
expect {
	timeout {puts "TESTING ERROR 0.1\n";exit}
	"Bad system call"
}
send -- "exit\r"
sleep 1

send -- "firejail --nox11 sleep 1 &\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
send -- "firejail --nox11 sleep 1 &\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"Child process initialized"
}
send -- "firejail --nox11 sleep 1 &\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
send -- "firejail --nox11 sleep 1 &\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Child process initialized"
}
send -- "firejail --nox11 sleep 1 &\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
after 100


send -- "cat /proc/firejail\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"sandbox pid"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"no connect unix"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"sandbox pid"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"no connect unix"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"sandbox pid"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"no connect unix"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"sandbox pid"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"no connect unix"
}
puts "\n"
