#!/bin/bash
SLEEP="10"

while [ 1 ]
do
	echo "hello"
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP &
	firejail sleep $SLEEP 
	firejail sleep $SLEEP
	ps aux
done
